[profile.default]
solc = "0.8.34"
remappings = [
    "@solady/=lib/solady/",
    "@forge-std/=lib/forge-std/",
    "@ctf-exchange-v2/src/=src/",
    "@ctf-exchange-v2/test/=test/",
]
ffi = true
gas_reports = ["*"]
out = "out"
optimizer_runs = 1000000
fs_permissions = [{ access = "read", path = "./artifacts/"}]

[profile.ci]
ffi = false

# fuzz settings
[profile.default.fuzz]
runs = 256
[profile.intense.fuzz]
runs = 10_000

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
wrap_comments = true
single_line_statement_blocks = "single"
